@startuml activity

!include https://hcm-commons.cfapps.eu10.hana.ondemand.com/iuml/skins
!include https://hcm-commons.cfapps.eu10.hana.ondemand.com/iuml/activity

|Application|
start

:Acquire Enqueue X;

|Enqueue Server|

:Check enqueue status;
if() then (Free)
:Set Enqueue;
:Set Status to Success;
else(Locked)
:Set Status to Failed;
endif

|Application|
:Check the Enqueue Server Result;
if() then(Failed)
|Application|
end
else(Success)
:Process Resource;
:Request Release of Enqueue X;
|Enqueue Server|
:Release Enqueue X;
endif

|Application|
stop
@enduml