@startuml activity

!include https://hcm-commons.cfapps.eu10.hana.ondemand.com/iuml/skins
!include https://hcm-commons.cfapps.eu10.hana.ondemand.com/iuml/activity

|Customer|
start
:Enter Shop;

while()
:Show Product Details;
if() then (Like It)
:Add to Shopping Cart;
else(No Thanks)
endif

endwhile(Finished Selection)
:Submit Order; 

|Order Processing| 

fork
:Check Availability;
fork again
:Request Payment Check;
|Payment Service Provider|
:Check Credit Limit;
|Order Processing|
endfork

if() then (Problem)
:Send Problem Description;
else(Ok)
:Send Order Confirmation;
:Trigger Delivery;
endif

stop

@enduml